### ISSUE TITLE
how can i use Element UI

### ISSUE THREAD

**Issue by zangtingjun** [vuejs/vue-web-component-wrapper#100]
I want to use Element UI in vue，vue cli is not compati with the package

```
vue:634 [Vue warn]: Error in callback for watcher "pickerVisible": "TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'."

found in

 <ElDatePicker> at packages/date-picker/src/picker.vue
```

**Comment by karol-f** [comment]
`vue-web-component-wrapper` is not intended to wrap such things. IMHO treat it like mini pieces of your own code.

If You want mini-apps like functionality you can try using alternative solutions e.g. `vue-custom-element`

**Comment by zangtingjun** [comment]
> want mini-apps

So far I've solved the global CSS problem using @telia/vue-web-component-wrapper-ie11，but the JS reference problem is still unresolved

**Comment by zangtingjun** [comment]
I have solved the problem using  vue-custom-element
