### ISSUE TITLE
Can't apply styles with Shadow Dom

### ISSUE THREAD

**Issue by shprink** [vuejs/vue-web-component-wrapper#2]
Hello,

I am building a Web Component Todo app comparison between several alternatives such as Polymer, Stencil, Angular Elements and now with Vue :)

Code: https://github.com/shprink/web-components-todo/tree/master/vue
Demo: https://wc-todo.firebaseapp.com/vue/

I cannot apply any style to Vue Web component:

![image](https://user-images.githubusercontent.com/1388706/36091445-1158340c-0fe4-11e8-9bab-9ff4c767c721.png)

I tried with`scoped` and `module` but without success. I use Chrome and the other implementations with Shadow DOM work.

Let me know what to do to apply styles.

thanks

**Comment by satyakresna** [comment]
Hi, I just test the [Julien's web-components-todo](https://github.com/shprink/web-components-todo/tree/master/vue) in Vue based on his code. When I run in local it shows like this. 
<img width="1442" alt="screen shot 2018-02-12 at 6 29 43 pm" src="https://user-images.githubusercontent.com/11099186/36093098-8e703cf6-1024-11e8-8d88-92c9329690d5.png">

I check the code that `<todo-input>` and `<todo-item>` aren't detected in **my-todo.vue**. But I check in his **main.js** the declaration of custom element is correct IMO.

```js
import Vue from 'vue';
import wrap from '@vue/web-component-wrapper';

Vue.config.productionTip = false

import MyTodo from './components/my-todo.vue';
import TodoInput from './components/todo-input.vue';
import TodoItem from './components/todo-item.vue';

window.customElements.define('my-todo', wrap(Vue, MyTodo));
window.customElements.define('todo-input', wrap(Vue, TodoInput));
window.customElements.define('todo-item', wrap(Vue, TodoItem));
```

**Comment by yyx990803** [comment]
Note this module isn't meant to be used with your custom setup, if you want styles in shadow DOM it assumes you are using it via the new vue-cli and building with `--target wc` or `--target wc-async`.

**Comment by shprink** [comment]
works thanks! https://wc-todo.firebaseapp.com/vue/

**Comment by steamypassion** [comment]
Is there a use case like allow user to insert their Snippets of HTML and CSS in Shadow DOM to prevent parent style cascade in the Custom Element. Any known alternative on this use case?
1) Reset CSS per Vue Components?
2) I can't figure how to loading Dynamic Elements with this library (Extra Performance)
3) Others?

**Comment by snirp** [comment]
> works thanks! https://wc-todo.firebaseapp.com/vue/

Care to explain what you did to make the styles work? Doesn't work in my project, but your setup looks more or less vanilla vue. Did you do anything specific to attach the <style> to the shadowDom?

**Comment by snirp** [comment]
Erm, wait a sec. That does not look like a web component at all. I see no shadow Dom. The build script looks like it should wrap a web component, but the demo link seems like a regular vue component.
