### ISSUE TITLE
Can't get slots to work

### ISSUE THREAD

**Issue by BryanKuiper** [vuejs/vue-web-component-wrapper#21]
I am trying to get pass a title to my wrapped web-component but it does not seem to work. Am I missing something?

index.html:

```
<body>
    <my-component>
        <h1 slot="main-title">This should be the title</h1>
    </my-component>
</body>

```

my-component.vue:

```
<template>
    <article>
        <div>
            <slot name="main-title">Place title here</slot>
        </div>
    </article>
</template>

```

The result is that I only see the default title and not my actual title.
Within vue, this kind of slots (not scoped) work just find, so I suspect that the wrapper does some things a little bit different.

Please help.

**Comment by BryanKuiper** [comment]
Additionally, this is what I do to transform it into a webcomponent:

```

import Vue from "vue";
import wrap from "@vue/web-component-wrapper";
import my-component from "./my-component";

Object
    .entries({ "my-component" : my-component })
    .map( ([ key, component ]) => [ key, wrap( Vue, component ) ] )
    .forEach( ([ name, element ]) => window.customElements.define( name, element ) );

```

**Comment by BryanKuiper** [comment]
Made a mistake. Forgot to pass the slot to the child component

**Comment by egucciar** [comment]
@BryanKuiper I'm new to vue and vue-wb-component-wrapper and having the same problem, what o you mean forgot to pass the slot to the child component?
