### ISSUE TITLE
Default casting of Boolean prop

### ISSUE THREAD

**Issue by DonNicoJs** [vuejs/vue-web-component-wrapper#3]
Using the version of vue-web-component-wrapper included with Vue cli version `3.0.0-beta.1`

I have noticed a strange / not documented behaviour of the auto casting of Boolean Props:

a prop defined as:

```js
props: {
  aBooleanProp: {
    type: Boolean,
    default: true
  }
}
```
will be set to false if the prop is omitted in the web component tag:

```html
<my-web-component />
```

I understand that this may be the expected behaviour in the case of web-components but since it differ from what happens in normal Vue development I think it should be documented.

**Comment by sylvainpolletvillard** [comment]
+1, default values should apply when omitting a boolean property.

Another example:

MyButton.vue:
```vue
<template>
  <button :class="{ red: red }">My Button</button>
</template>

<style scoped>
button.red {
  background: red;
}
</style>

<script>
export default {
  name: "MyButton",
  props: {
    red: {
      type: Boolean,
      default: true
    }
  }
};
</script>
```

main.js:
```js
import Vue from 'vue'
import wrap from '@vue/web-component-wrapper'
import MyButton from "./components/MyButton.vue"

new Vue({
  render: h => h(MyButton),
}).$mount('#app')


const CustomElement = wrap(Vue, MyButton)
window.customElements.define('my-button', CustomElement)
```

index.html:
```html
<body>
  <div id="app"></div>
  <my-button></my-button>
  <!-- built files will be auto injected -->
</body>
```

result:
![image](https://user-images.githubusercontent.com/566536/64440960-3b1adc80-d0cd-11e9-8bda-168249fd6352.png)

This is not consistent and makes the use of boolean properties very difficult for the moment.

**Comment by sodatea** [comment]
This is an anti-pattern actually: https://eslint.vuejs.org/rules/no-boolean-default.html

**Comment by sylvainpolletvillard** [comment]
Interesting... This anti-pattern comes from a [very popular library](https://github.com/buefy/buefy/blob/dev/src/components/field/Field.vue#L63) which is using eslint-vue. I wonder why it has not been spotted before.

Anyway, the issue remains that this case should be handled the same way between vue and vue-web-component-wrapper.
