### ISSUE TITLE
Can i prop Object and Array to my custom element ?

### ISSUE THREAD

**Issue by biigpongsatorn** [vuejs/vue-web-component-wrapper#33]
I use this lib and I want to prop `Object` and `Array` to `my-custom-element` but it past `String` to my custom element

```html
<template>
  <chat-vue-web-component-wrapper :id="id" :name="name" :prefix="prefix" :thread="thread" :msg="msg"/>
</template>

<script>
export default {
  name: 'VueWebComponentWrapper',
  data () {
    return {
      thread: {
        img: 'https://vignette.wikia.nocookie.net/line/images/b/b7/1511.png/revision/latest?cb=20150809133444'
      },
      id: 99271,
      prefix: 'Mr.',
      name: 'Brown',
      msg: [
        { sender: 'user', message: 'Hello :)' },
        { sender: 'user', message: 'How are you ?' }
      ]
    }
  }
}
</script>
```

I built it with `vue-cli-service`.
Thanks.

**Comment by LinusBorg** [comment]
That's normal. All attributes on a custom elements are converted to strings (that'S just the spec). 

As explained [here](https://github.com/vuejs/vue-web-component-wrapper#props) this library typecasts props that are of type `Boolean` or `Number`, but nothing else.

So you will have to `JSON.serialize()` them ebcore you pass them, and use `JSON.parse` to get objects& arrays again in the component, usually through a computed prop.

**Comment by biigpongsatorn** [comment]
@LinusBorg  Thank you 👍
