### ISSUE TITLE
can't show font awesome icons

### ISSUE THREAD

**Issue by ouarrtaha** [vuejs/vue-web-component-wrapper#35]
i want to use font awesome icons in my web component.
i used this package https://github.com/FortAwesome/vue-fontawesome
it works in dev mode with "vue-cli-service serve"
but when building with "vue-cli-service build --target wc --name app 'src/app.vue'" the icons aren't shown

**Comment by karol-f** [comment]
Prepare demo on e.g. https://codesandbox.io/s/vue . Also what your browser's console is telling? Maybe links to grab font/SVG are broken?

**Comment by hardjob** [comment]
I fixed that by pulling out the @font-face rules out of my element; mentionned here http://robdodson.me/at-font-face-doesnt-work-in-shadow-dom/
(i'm working on a chrome extension that inject element made by vue, so i have to inject the font-face rules at header section of current document)
I don't know if there is a better approach than that, i'm hopping to encapsulate all my needed style in the Shadow DOM

**Comment by sodatea** [comment]
See https://github.com/FortAwesome/vue-fontawesome#web-components-with-vue-web-component-wrapper
