### ISSUE TITLE
"export 'default' (imported as 'biTable') was not found in '~root/./src/main.js?shadow' 

### ISSUE THREAD

**Issue by addijhaq** [vuejs/vue-web-component-wrapper#36]
Having issue using with vue-cli-service 

when building module using this command
```vue-cli-service build --target wc --name bi-table ./src/main.js```

i get this warning message. 
```"export 'default' (imported as 'biTable') was not found in '~root/./src/main.js?shadow'```

I'm also not getting my css injected in my webcomponent. 

Any help gladly appreciated.

**Comment by karol-f** [comment]
You have to target *.vue files https://github.com/vuejs/vue-web-component-wrapper/issues/16#issuecomment-406626212

**Comment by addijhaq** [comment]
yes, thank you i figured it out! much appreciated

**Comment by zhanghaofei** [comment]
@addijhaq 我也遇到了此问题，你是怎么解决的？

**Comment by claudiolcastro** [comment]
@karol-f @yyx990803  when I put my target directly to my *.vue component, I'm not having access to the vue-router. How can I solve this?
