### ISSUE TITLE
Missing Css!!

### ISSUE THREAD

**Issue by mailok** [vuejs/vue-web-component-wrapper#4]
hi!, I constructed a component using Vuetify (https://vuetifyjs.com/), then I wanted to make a Webconponent and the result was not good, Missing Css and icons.

Component:
![wrap1](https://user-images.githubusercontent.com/3769277/36693719-2e86091a-1b0a-11e8-98f8-55f5330d9fd2.PNG)

WebComponent
![wrap2](https://user-images.githubusercontent.com/3769277/36693720-2fd6834e-1b0a-11e8-8d44-00c4db57c5bb.PNG)

**Comment by yyx990803** [comment]
Please provide a minimal reproduction and post it to vue-cli's repo.

**Comment by mailok** [comment]
But why in vue-cli's repo if my problem is with webcomponent ?

**Comment by yyx990803** [comment]
Oh I assumed you are using this via `vue-cli`'s web component mode.

This repository actually is not meant to be used without `vue-cli`. Either way you will need to provide a reproduction.
