### ISSUE TITLE
Make global vue smaller?

### ISSUE THREAD

**Issue by filipbech** [vuejs/vue-web-component-wrapper#50]
I really like the simplicity of this approach to wrapping vue-components as custom-elements, but I cant figure out how to make the vuejs bundle (not my code or the wrapper - but the global vue) smaller. I'm building a very simple components and doesnt really use many features, so I would think, I could shrink the bundle considerably. 
I cant find any "official" way of doing this, but am I missing something, is there a workaround/hack for it, or is it jut not possible?

**Comment by yyx990803** [comment]
Unfortunately there isn't really a way to do this - the idea is that you can have multiple Vue-based custom elements on the page and they'd all share the same global Vue - that means you can't really know ahead of time what features these elements are going to use, so the global Vue must include every possible feature (even if we are able to tree-shake it like in Vue 3).

With Vue 3's tree-shaking capabilities, it's possible to provide a build output that includes a tree-shaken version of Vue runtime into your element, but that baseline will still be around 10kb gzipped.

A proper use case for Vue w/ custom elements is shipping a decent number of custom elements sharing the same Vue runtime, making the overhead acceptable. But for one-off, single custom elements that focus on small size, it's probably better to use something like [Svelte](https://svelte.technology/) or [Stencil](https://stenciljs.com/) which are optimized for the latter case.

**Comment by filipbech** [comment]
Thanks for the feedback! I appreciate you taking the time...
