### ISSUE TITLE
How is this different from karol-f/vue-custom-element ?

### ISSUE THREAD

**Issue by diogosalazar** [vuejs/vue-web-component-wrapper#6]
Hi, could you kindly explain how this project expands on `karol-f/vue-custom-element` ?
Thank you

**Comment by ggregg** [comment]
Karol-f support ie11 :)

**Comment by karol-f** [comment]
@diogosalazar From my point of view the main points of `vue-web-component-wrapper` are:
* you can automagically insert styles from *.vue files into Shadow DOM 
* `vue-cli` support
* `slots` are not static but dynamic (thanks to use of Mutation Observer)
* support only for newer browsers

**Comment by diogosalazar** [comment]
Thanks @karol-f for the differences breakdown.

**Comment by allenhwkim** [comment]
Is there a way to support IE11 using polyfill?
