### ISSUE TITLE
svg sprite no display in shadowDom  (ios 12以下)

### ISSUE THREAD

**Issue by SayGoodBey** [vuejs/vue-web-component-wrapper#61]
svg sprite no display in shadowDom ,but  display under normal document

**Comment by sodatea** [comment]
Please provide a runnable reproduction repo.

**Comment by SayGoodBey** [comment]
[https://codesandbox.io/s/vue-template-8crp3?fontsize=14](url) 
这是demo  因为某些原因svg雪碧图后期要用file方式加载 ，所以暂时用了这种把svg写在页面内的方式  ios 12以下显示不出来   android 跟12以上没问题

**Comment by sodatea** [comment]
https://bugs.webkit.org/show_bug.cgi?id=174977
iOS bug.
